Don't include 7zip in the linux package

diff --git a/.yamato/build.yml b/.yamato/build.yml
--- a/.yamato/build.yml
+++ b/.yamato/build.yml
@@ -16,9 +16,17 @@ linux:
     - cp Artistic.txt ./build/
     - cp libyasm/bitvect.c ./build/
     - cp libyasm/bitvect.h ./build/
-    - cd build && wget https://public-stevedore.unity3d.com/r/public/7zip-linux-x64/24.07_9eb0ed9_c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b.zip
-    - cd build && unzip 24.07_9eb0ed9_c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b.zip
-    - cd build && ./7za a yasm-linux-x64.7z *
+    - |
+      set -euo pipefail
+      wget https://public-stevedore.unity3d.com/r/public/7zip-linux-x64/24.07_9eb0ed9_c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b.zip
+      actual_hash=$(shasum -a 256 24.07_9eb0ed9_c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b.zip | cut -f1 -d' ')
+      if [ "$actual_hash" != c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b ] ; then
+        echo "Error: 7zip-linux-x64 package hash does not match"
+        exit 1
+      fi
+      unzip 24.07_9eb0ed9_c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b.zip
+      cd build
+      ../7za a yasm-linux-x64.7z *
   artifacts:
     build:
       paths:
